#define NUMBER_OF_CHARACTERS_FULL 94
#define NUMBER_OF_CHARACTERS_PHONE 83
#define NUMBER_OF_CHARACTERS_SIMPLE 63
#define WIDTH 256
#define HEIGHT 196
#define PASSWORD_LENGHT 30

#define KEYBOARD_KEYS 40
#define KEYBOARD_BUTTONS_OFFSET 2
#define UPPER_MODE 0
#define LOWER_MODE 1
#define SYMBOLS_MODE 2

#define BUTTON_SIZE 22

#define SPRITE_SIZE 1024
#define SPRITESHEETS_SIZE 1024 * 200
